import unittest
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def read(relative_path: str) -> str:
    return (ROOT / relative_path).read_text(encoding="utf-8")


class StudyProtocolStaticTest(unittest.TestCase):
    def test_reading_protocol_matches_hci_study_design(self):
        reading_page = read("frontend/leeswijs/src/pages/ReadingPage.tsx")
        session_router = read("backend/app/routers/session.py")

        self.assertIn("const READINGS_PER_PHASE = 3;", reading_page)
        self.assertIn("const TARGET_WORDS_PER_PHASE = 10;", reading_page)
        self.assertIn("READINGS_PER_PHASE = 3", session_router)
        self.assertIn("FINAL_STUDY_PHASE = 2", session_router)

    def test_participant_copy_does_not_expose_ai_terms(self):
        participant_files = [
            "frontend/leeswijs/src/pages/OnboardingPage.tsx",
            "frontend/leeswijs/src/pages/ReadingPage.tsx",
            "frontend/leeswijs/src/pages/ReadingSessionPage.tsx",
            "frontend/leeswijs/src/pages/SystemTransitionPage.tsx",
            "frontend/leeswijs/src/components/DelayedVocabReminder.tsx",
        ]
        blocked_patterns = (
            r"\bAI\b",
            r"\bGemini\b",
            r"\bLLM\b",
            r"generated by",
            r"artificial intelligence",
        )

        visible_copy = "\n".join(read(path) for path in participant_files)

        for pattern in blocked_patterns:
            self.assertIsNone(re.search(pattern, visible_copy, re.IGNORECASE))


if __name__ == "__main__":
    unittest.main()
